### ISSUE TITLE
CV promotion not working anymore with Satellite 6.8?

### ISSUE THREAD

**Issue by fr3duard0** [RedHatSatellite/ballista#18]
Hello,

We just upgraded from Satellite 6.6 to Satellite 6.8, and from that date on the "promote-cv" is not working anymore.
We also tested the "chain-publish" and "cleanout-view" and they are working fine with the exact same parameters...

Output:
`[root@examplesvr ~]# /usr/local/bin/ballista.py -c /usr/local/etc/release78.ini promote-cv Prod promote
Starting new HTTPS connection (1): examplesvr.intern.example.com
promoting XXX_Custom_78 to environment Prod
Resetting dropped connection: examplesvr.intern.example.com
promoting RHEL78-os to environment Prod
Resetting dropped connection: examplesvr.intern.example.com
promoting CCV-RHEL78-leapp to environment Prod
`

Is this a known issue? 
Do you know what could cause this error as the connections work fine with other ballista options (same ini file)

Thanks :)
Frederik

**Comment by yhekma** [comment]
Hia @fr3duard0 

I am afraid this codebase is not really maintained anymore. I personally have moved on to other things and haven't touched Satellite in years. If you want you can of course look into it yourself and do a pr, I'll happily look at it and merge it if it solves your problem (although you could of course also just fork the whole thing).
I must admit I sort of assumed most of the functionality Ballista provides would be integrated into Satellite by now? When I and @joeyloman originally wrote this thing it was to make the whole thing bareable since it was, imo, released before the tooling was really up to snuff. Now that's 5 years ago so it might be worth checking if you actually need this thing in the first place ;)
